version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: Questionpro_db
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8082"